import 'dart:ui';

import 'package:flex_color_scheme/flex_color_scheme.dart';

final lightTheme = FlexThemeData.light(
  colors: FlexSchemeColor.from(
    brightness: Brightness.light,
  primary: const Color(0xff1145a4),
  primaryContainer: const Color(0xffacc7f6),
  secondary: const Color(0xff376bca),
  secondaryContainer: const Color(0xffcfdbf2),
  tertiary: const Color(0xffb61d1d),
  tertiaryContainer: const Color(0xffec9f9f),
  error: const Color(0xffb00020),
  errorContainer: const Color(0xfffcd8df),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 7,
  tooltipsMatchBackground: true,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 9.0,
    filledButtonRadius: 9.0,
    elevatedButtonRadius: 9.0,
    outlinedButtonRadius: 9.0,
    outlinedButtonBorderWidth: 1.5,
    switchThumbFixedSize: true,
    inputDecoratorRadius: 9.0,
    inputDecoratorBorderWidth: 0.5,
    fabUseShape: true,
    fabRadius: 9.0,
    chipRadius: 9.0,
    popupMenuElevation: 0.0,
    alignedDropdown: true,
    dialogRadius: 9.0,
    datePickerDialogRadius: 9.0,
    timePickerDialogRadius: 9.0,
    useInputDecoratorThemeInDialogs: true,
    appBarScrolledUnderElevation: 0.0,
    drawerRadius: 9.0,
    drawerElevation: 0.0,
    drawerIndicatorRadius: 9.0,
    menuRadius: 9.0,
    menuBarRadius: 9.0,
    navigationBarBackgroundSchemeColor: SchemeColor.primary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
);

final darkTheme = FlexThemeData.dark(
  colors: FlexSchemeColor.from(
    brightness: Brightness.dark,
  primary: const Color(0xffc4d7f8),
  primaryContainer: const Color(0xff577cbf),
  secondary: const Color(0xffdde5f5),
  secondaryContainer: const Color(0xff1145a4),
  tertiary: const Color(0xfff1bbbb),
  tertiaryContainer: const Color(0xffcb6060),
  error: const Color(0xffcf6679),
  errorContainer: const Color(0xffb1384e),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 13,
  tooltipsMatchBackground: true,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    blendTextTheme: true,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 9.0,
    filledButtonRadius: 9.0,
    elevatedButtonRadius: 9.0,
    outlinedButtonRadius: 9.0,
    outlinedButtonBorderWidth: 1.5,
    switchThumbFixedSize: true,
    inputDecoratorRadius: 9.0,
    inputDecoratorBorderWidth: 0.5,
    fabUseShape: true,
    fabRadius: 9.0,
    chipRadius: 9.0,
    popupMenuElevation: 0.0,
    alignedDropdown: true,
    dialogRadius: 9.0,
    datePickerDialogRadius: 9.0,
    timePickerDialogRadius: 9.0,
    useInputDecoratorThemeInDialogs: true,
    appBarScrolledUnderElevation: 0.0,
    drawerRadius: 9.0,
    drawerElevation: 0.0,
    drawerIndicatorRadius: 9.0,
    menuRadius: 9.0,
    menuBarRadius: 9.0,
    navigationBarBackgroundSchemeColor: SchemeColor.primary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
);


